FROM python:3.8-slim-buster

ENV PORT=5000

WORKDIR /app

# Install requirements
COPY requirements.txt requirements.txt
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy files
COPY . .    

# Start the Flask app using Gunicorn
CMD gunicorn --bind 0.0.0.0:$PORT wsgi:app


